config/routes.rb
Rails.application.routes.draw do
  devise_for :companies,controllers: { registrations: 'devise/registrations' }

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  root 'pages#index'

  get 'pages/show'
  
  resources :comments
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         #:confirmable, 
         :lockable, :timeoutable, :trackable
  
  with_options presence: true do
    validates :nickname
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
        devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end
end

app/controllers/companies/passwords_controller.rb
# frozen_string_literal: true

class Companies::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/companies/sessions_controller.rb
# frozen_string_literal: true

class Companies::SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    root_path
  end

  private
  def sign_in_required
      redirect_to new_company_session_url unless company_signed_in?
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/companies/unlocks_controller.rb
# frozen_string_literal: true

class Companies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #before_action :sign_in_required, only: [:show]
  
  def index
  end

  def show
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource) 
    root_path
  end

  private
  def sign_in_required
      redirect_to new_user_session_url unless user_signed_in?
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KakomoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    
    <!--空白の原因--
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    空白の原因-->
    <%= yield %>

  </body>
  
  <footer class="footer">
    <p class="copyright">
      Copyright(C) Kakomo ALL RIGHTS RESERVED.
    </p>
  </footer>

</html>

app/views/pages/index.html.erb
<header class='top-page-header'>
      <div class ="left-header">
       <%= link_to image_tag("kakomo-logo01.jpg", class:"kakomo-icon"), "/" %>
      </div>
      <div class="right-header">
        <% if user_signed_in? %>
          <strong><%= link_to current_user.nickname, pages_show_path %></strong>
          <%= link_to 'プロフィール変更', edit_user_registration_path %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to '個人新規登録', new_user_registration_path %>
          <%= link_to '個人ログイン', new_user_session_path %>
        <% end %>
        <% if company_signed_in? %>
          <strong><%= link_to current_company.email, pages_show_path %></strong>
          <%= link_to '企業プロフィール変更', edit_company_registration_path %>
          <%= link_to 'ログアウト', destroy_company_session_path, method: :delete %>
        <% else %>
          <%= link_to '企業新規登録', new_company_registration_path %>
          <%= link_to '企業ログイン', new_company_session_path %>
        <% end %>
      </div>
</header>

<main>
  <%# 画面上部の「おいしいを、囲もう」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      「おいしい」を、囲もう。
    </h2>
    <p class='service-explain'>
      離れた場所にいても、同じおつまみを食べよう。
    </p>
    <p class='service-explain'>
      kakomoは、オンライン飲み会のためのコミュニケーションフード宅配サービスです。
    </p>
  </div>
  <%# /画面上部の「おいしいを、囲もう」帯部分  %>
  
  <%# 「Kakomoが届けたいこと」部分 %>
  <div class='selling-point-contents'>
    <h2 class='title'>
      Kakomoが届けたいこと
    </h2>
    <ul class='point-lists'>
      <li class='list'>
        <%= image_tag "kakomo-snaq03.jpg", class:"list-pict" %>
        <h3 class='point-list-text'>
          <span class='point-list-blue-text'>「おいしい」共通体験</span>
        </h3>
        <p class='point-list-description'>
          離れた場所にいても、同じおつまみを囲めば従来の飲み会のような一体感が生まれます。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "kakomo-snaq01.jpg", class:"list-pict" %>
        <h3 class='point-list-text'>
          <span class='point-list-blue-text'>おつまみ診断</span>
        </h3>
        <p class='point-list-description'>
          お好きな料理や飲み会のムードを答えるだけ。ぴったりなおつまみを提案します。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "kakomo-snaq07.jpg", class:"list-pict" %>
        <h3 class='point-list-text'>
          <span class='point-list-blue-text'>好きな場所にお届け</span>
        </h3>
        <p class='point-list-description'>
          ご自宅やお仕事場のポストにおつまみセットをお届け。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "kakomo-snaq04.jpg", class:"list-pict" %>
        <h3 class='point-list-text'>
          <span class='point-list-blue-text'>お好みにアレンジ</span>
        </h3>
        <p class='point-list-description'>
          アレルギー成分などご指定ください。一部の方のみ抜くことも可能です。
        </p>
      </li>
    </ul>
  </div>
  <%# /「Kakomoが届けたいこと」 %>
  <%# 「Kakomoで商品が届くまで」 %>
  <div class='how-to-contents'>
    <h2 class='title'>
      Kakomoで商品が届くまで
    </h2>
    <ul class='how-to-lists'>
      <li class='list'>
        <%= image_tag "kakomo-howto01.png", class:"list-pict" %>
        <h3 class='how-to-list-text'>
          おつまみ診断
        </h3>
        <p class='how-to-list-description'>
          食の好みや除外したい食材などの情報をご入力ください。ご購入手続きは診断の後にございます。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "kakomo-howto02.jpg", class:"list-pict" %>
        <h3 class='how-to-list-text'>
          ポストにお届け
        </h3>
        <p class='how-to-list-description'>
          ご自宅やお仕事場のポストに商品をお届け。置き配などのご指定も承ります。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "kakomo-howto03.jpg", class:"list-pict" %>
        <h3 class='how-to-list-text'>
          飲み会スタート
        </h3>
        <p class='how-to-list-description'>
          おつまみを開いて、おうちのお酒で乾杯！（お酒はセットに含まれません）
        </p>
      </li>
    </ul>
  </div>
  <%# /「Kakomoで商品が届くまで」 %>
  <%# 下部広告部分 %>
  <div class='ad-footer-contents'>
    <p class='ad-footer-explain'>
     Kakomoで「おいしい」の共通体験を。
    </p>
    <p class='ad-footer-explain'>
     Kakomoはおつまみに特化した宅配サービスです。
    </p>
    <p class='ad-footer-explain'>
     今夜は画面の向こうのあの人と、一緒につまみましょう。
    </p>
  </div>
<%# /下部広告部分 %>
</main>

<div class='footer'>
  <div class='footer-contents'>
    <div class='kakomo-details'>
      <h2 class='footer-content-head'>Kakomoについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'Kakomo利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='kakomo-details'>
      <h2 class='footer-content-head'>Kakomoを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to '出店一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='kakomo-details'>
      <h2 class='footer-content-head'>Kakomoについて</h2>
      <ul>
        <li><%= link_to 'Kakomoガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'ロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("kakomo-logo02.jpg", class:"logo-white"), "#" %>
</div>

app/views/pages/show.html.erb
<header class="registarion-header">
  <%= link_to image_tag("kakomo-logo04.jpg", class:"kakomo-logo"), "/" %>
    <nav>
      <% if user_signed_in? %>
        <strong><%= link_to current_user.email, pages_show_path %></strong>
        <%= link_to 'プロフィール変更', edit_user_registration_path %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to '新規登録', new_user_registration_path %>
        <%= link_to 'ログイン', new_user_session_path %>
      <% end %>
    </nav>
</header>


<p>ユーザー用ページです。</p>